package transform.DependenceGraph;

public enum TYPE
{
    /*ENTRANCE, ASSIGN, CONDITION, DECLARATION, RETURN, FORLOOP, SELECTION, CASE, BREAK*/
	ASSIGN, ENTRANCE, DEFINE, CONDITION, SWITCH, CASE, RETURN, FORLOOP, PRINT
}
